### ISSUE TITLE
cache subprovider catastrophic failure

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#1201]
reported by aragon - not sure what version of metamask they are using

```TypeError: Cannot read property 'number' of undefined
    at BlockCacheProvider._handleRequest (metamask://app/scripts/background.js:108808:65)
    at Stoplight.<anonymous> (metamask://app/scripts/background.js:108781:10)
    at Stoplight.g (metamask://app/scripts/background.js:85157:16)
    at Stoplight.EventEmitter.emit (metamask://app/scripts/background.js:85088:20)
    at Stoplight.go (metamask://app/scripts/background.js:110361:8)
    at Web3ProviderEngine.<anonymous> (metamask://app/scripts/background.js:108751:17)
    at Web3ProviderEngine.g (metamask://app/scripts/background.js:85157:16)
    at Web3ProviderEngine.EventEmitter.emit (metamask://app/scripts/background.js:85088:20)
    at Web3ProviderEngine._setCurrentBlock (metamask://app/scripts/background.js:102285:8)
    at metamask://app/scripts/background.js:102275:12
```
this is the exception and the body:
```"{"jsonrpc":"2.0","result":{"author":"0x00e6d2b931f55a3f1701c7389d592a7778897879","difficulty":"0xfffffffffffffffffffffffffffffffe","extraData":"0xd5830105048650617269747986312e31352e31826c69","gasLimit":"0x47b760","gasUsed":"0x0","hash":"0xc257bce3cab3771238b51fef7e7f574b40de9a0874df9a4f6a5b8e4f4db29c08","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x00e6d2b931f55a3f1701c7389d592a7778897879","number":"0x257b9","parentHash":"0xc1edef1989eaa688d5b6b0a3d6c46838afb2431615c27d92a5dae9d8d838f616","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sealFields":["0x16309bfc","0x2d9f5860447926e66c6e61d469de0945f2a33978cd6117f0e215583e9be3b7226dc4085e759002608219710c50cd5e236539636db2d9f4880f773bf4645709fc01"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","signature":"2d9f5860447926e66c6e61d469de0945f2a33978cd6117f0e215583e9be3b7226dc4085e759002608219710c50cd5e236539636db2d9f4880f773bf4645709fc01","size":"0x243","stateRoot":"0x6a7a0933188673269f6ea5e090878be97c8eb9e6ba87ea7bcf651149f29a7003","step":"372284412","timestamp":"0x58c26ff0","totalDifficulty":"0x14aa000000000000000000000004861fd6ac","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":1489137645683319}
"```
(edited)

[1:25]  
and the full stack trace

[1:25]  
 ```BlockCacheProvider._handleRequest (cache.js:95)
(anonymous function) (cache.js:68)
g (background.js:85157)
EventEmitter.emit (background.js:85088)
Stoplight.go (stoplight.js:18)
(anonymous function) (cache.js:38)
g (background.js:85157)
EventEmitter.emit (background.js:85088)
Web3ProviderEngine._setCurrentBlock (index.js:184)
(anonymous function) (index.js:174)
(anonymous function) (index.js:222)
Web3ProviderEngine._inspectResponseForNewBlock (index.js:231)
(anonymous function) (index.js:131)
(anonymous function) (async.js:359)
replenish (async.js:876)
iterateeCallback (async.js:866)
(anonymous function) (async.js:843)
async.eachSeries.resultObj.id (index.js:111)
(anonymous function) (async.js:3025)
replenish (async.js:881)
iterateeCallback (async.js:866)
(anonymous function) (async.js:843)
async.eachSeries.resultObj.id (index.js:111)
(anonymous function) (async.js:3025)
replenish (async.js:881)
iterateeCallback (async.js:866)
(anonymous function) (async.js:843)
async.eachSeries.resultObj.id (index.js:111)
(anonymous function) (async.js:3025)
replenish (async.js:881)
iterateeCallback (async.js:866)
(anonymous function) (async.js:843)
async.eachSeries.resultObj.id (index.js:111)
(anonymous function) (async.js:3025)
replenish (async.js:881)
iterateeCallback (async.js:866)
(anonymous function) (async.js:843)
async.eachSeries.resultObj.id (index.js:111)
(anonymous function) (async.js:3025)
replenish (async.js:881)
iterateeCallback (async.js:866)
(anonymous function) (async.js:843)
async.eachSeries.resultObj.id (index.js:111)
(anonymous function) (async.js:3025)
replenish (async.js:881)
iterateeCallback (async.js:866)
(anonymous function) (async.js:843)
async.eachSeries.resultObj.id (index.js:111)
(anonymous function) (async.js:3025)
replenish (async.js:881)
(anonymous function) (async.js:885)
eachLimit$1 (async.js:3114)
(anonymous function) (async.js:917)
end (index.js:106)
(anonymous function) (rpc.js:64)
cbOnce (index.js:62)
loadFunc (index.js:129)
readystatechange (index.js:68)
```

**Comment by kumavis** [comment]
resolved this today/
