### ISSUE TITLE
improve "PortDuplexStream - disconnected" error

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#960]
real error is not shown. stream swallows error. we need to prevent the stream from intercepting the errors

simondlr [11:50 PM]  
Hey guys. Not sure what this issue is. User of Token Factory sent me this log. I tested on my Chrome with same setup and it works fine. So maybe a Metamask bug? Any help in venturing through this rabbit hole?

—
```MetaMask - injected web3
app.js:7801 Download the React DevTools for a better development experience: https://fb.me/react-devtools
app.js:67437 provider is available
app.js:67033 Contract
app.js:67067 decimals present
app.js:67080 name present
app.js:67091 symbol present
app.js:67075 BigNumber
app.js:67041 BigNumber
app.js:67086 Paco Jokinen Bucks
app.js:67098 PACJ
app.js:49908 Array[5]
app.js:49899 0x4c2b3fec38465d4d70e47c5cfb6848d12352d5f7ff1edd2a03c1857631cc9a15
app.js:49830 0x4c2b3fec38465d4d70e47c5cfb6848d12352d5f7ff1edd2a03c1857631cc9a15 transfer
3app.js:49803 processing
app.js:32496 Error in loadTxData Array[1]
(anonymous) @ app.js:32496
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:2693 Error: PortDuplexStream - disconnected
    at PortDuplexStream._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:268)
    at doWrite (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4997)
    at writeOrBuffer (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4986)
    at PortDuplexStream.Writable.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4924)
    at PostMessageStream.ondata (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4068)
    at PostMessageStream.EventEmitter.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:2693)
    at readableAddChunk (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:3739)
    at PostMessageStream.Readable.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:3698)
    at PostMessageStream._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:3346)
EventEmitter.emit @ chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:2693
```

kumavis [11:51 PM]  
damn streams swallowing the real errors....

new messages
simondlr [11:52 PM]  
:confused:

**Comment by simondlr** [comment]
More info:

```
Error in conversion. SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:521:31
From previous event:
    at Request.RP$exposed [as then] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:114035:61)
    at ConfigManager.updateConversionRate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:520:80)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2204:30
(anonymous) @ config-manager.js:314
https://mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
index.js:163 Error: Internal XMLHttpRequest Error
    at loadFunc (index.js:127)
    at XMLHttpRequest.readystatechange (index.js:68)
cb @ index.js:163
config-manager.js:314
```

**Comment by Zanibas** [comment]
@simondlr that specific error you posted isn't related to PortDuplexStream, but is related to our currency conversion API currently being borked. Referenced by #753

**Comment by simondlr** [comment]
@Zanibas thanks! :)

**Comment by kumavis** [comment]
@simondlr may have resolved this, please keep a look out for it after we publish the big change

**Comment by kumavis** [comment]
Duplicate of https://github.com/MetaMask/metamask-plugin/issues/930
also - we deployed a fix for this. if you encounter this again, please let us know.
